version: '3.3'
services:
  app:
    image: golang:1.19-alpine3.16
    container_name: golang_container
    environment:
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASS=${POSTGRES_DB_PASS}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_HOST=postgresdb
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:${SERVER_PORT}
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    command: "go run /app/main.go"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - DATABASE_PORT=${POSTGRES_DB_PORT}
    container_name: postgres_container
    ports:
      - '1234:${POSTGRES_DB_PORT}'
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
      image: migrate/migrate
      container_name: migrate_container
      volumes:
        - ./migrations:/migrations
      command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_DB_USER}:${POSTGRES_DB_PASS}@postgresdb:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?sslmode=disable", "up", "3"]
      depends_on:
        - postgresdb

volumes:
  postgres-data-volume:
